version: '3.8'

services:
  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
    depends_on:
      - mysql-db
    networks:
      - app_net

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      - mysql-db
    networks:
      - app_net

  backend-2:
    build: ./backend
    container_name: backend-2
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      - mysql-db
    networks:
      - app_net

  backend-3:
    build: ./backend
    container_name: backend-3
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      - mysql-db
    networks:
      - app_net

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - 80
    depends_on:
      - backend
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
      - backend-2
      - backend-3
    networks:
      - app_net

volumes:
  mysql_data:

networks:
  app_net:
    driver: bridge
